.travis.yml
Dockerfile
Makefile
hack/build.sh

switch to multi-stage Dockerfile, simplify Makefile

---

README.md

I think this is all that is needed.
Signed-off-by: Carlisia <carlisia@vmware.com>

Update docs with plugin flag

---

backupstoragelocation.md
volumesnapshotlocation.md

PR 4 of 4 for https://github.com/vmware-tanzu/velero/issues/2003
cc @nrb @carlisia @prydonius

revise BSL and VSL docs using commented YAML

---

README.md

Signed-off-by: Ashish Amarnath <ashisham@vmware.com>

Fix doc bugs and clean markdown lint

---

Dockerfile

bug fix: change container group to nogroup

---

README.md

update docs for v1.0.1 release

---

README.md

Updated the compatibility matrix and modified some links to get auto-redirect to latest versioned docs.

docs updates for Velero v1.3.0 release

---

README.md

Signed-off-by: Carlisia <carlisia@vmware.com>

Update docs to reference Velero 1.4.0

---

changelogs/unreleased/30-skriss

remove changelog files that have already been released

---

README.md

should be AZURE_SUBSCRIPTION_ID instead of SUBSCRIPTION_ID

Fixed wrong environment variable in Readme

---

README.md

Signed-off-by: Ashish Amarnath <ashisham@vmware.com>
Fixes #42

📖 document node selector for linux

---

README.md
changelogs/CHANGELOG-1.1.1.md
changelogs/unreleased/51-gitirabassi
changelogs/unreleased/52-stephanwehr

Signed-off-by: Ashish Amarnath <ashisham@vmware.com>

changelogs and compatibility matrix update

---

Makefile
hack/release-tools/changelog.sh

Signed-off-by: Nolan Brubaker <brubakern@vmware.com>

Add changelog script

---

.gitignore
tilt-provider.json

Needed for vmware-tanzu/velero#3119.
Signed-off-by: Carlisia <carlisia@vmware.com>

Add Tilt setup

---

README.md

Direct new issues to the core Velero repo in order to reduce number of places we have to check, and to get better support for GitHub Projects.
Signed-off-by: Nolan Brubaker <brubakern@vmware.com>

Update README with new issue filing process

---

README.md

Solves https://github.com/vmware-tanzu/velero/issues/3158

Security configuration Azure Storage Account with AKS

---

changelogs/CHANGELOG-1.2.0.md
changelogs/unreleased/85-justbert
changelogs/unreleased/90-zubron

Signed-off-by: Carlisia <carlisia@vmware.com>

Update changelog for v1.2.0

---

Dockerfile

Change the base image to distroless

---

README.md

Update the doc to reference the latest version of azure plugin image

---

changelogs/CHANGELOG-1.3.1.md

Add changelog for 1.3.1

---

README.md

Update the README for the new release

Update the README for the new release

---

README.md
changelogs/CHANGELOG-1.4.0.md
changelogs/unreleased/114-ywk253100

Update changelog and README for 1.4.0

Update changelog and README for 1.4.0

---

.github/workflows/pr.yaml
.github/workflows/push.yml
Dockerfile

Pin the version of golang and distroless image

Pin the version of golang and distroless image

---

.github/auto-assignees.yml
Dockerfile

Bump up busybox version from 1.33.1 to 1.34.1

Bump up busybox version

---

changelogs/CHANGELOG-1.4.1.md

Signed-off-by: Ming <mqiu@vmware.com>

Add changelog for v1.4.1

---

go.mod
go.sum
velero-plugin-for-microsoft-azure/volume_snapshotter.go

Related to https://github.com/vmware-tanzu/velero/issues/4608

Support for zone-redundant storage (ZRS) managed disks

---

Dockerfile

Specify the user/group to run the image

Specify the user/group to run the image

---

README.md

Update README to include the supporting for ZRS disks

Update README to include the supporting for ZRS disks

---

.github/auto-assignees.yml

So Long, and Thanks for All the Fish.

Remove jenting from maintainers

---

.github/workflows/pr.yaml
.github/workflows/push.yml
Dockerfile
changelogs/CHANGELOG-1.5.1.md

Signed-off-by: Ming <mqiu@vmware.com>

Bump up golang version to 1.17.13

---

changelogs/CHANGELOG-1.5.2.md

Add changelog for 1.5.2

---

README.md
changelogs/CHANGELOG-1.6.0.md

Add changelog for 1.6.0

---

Dockerfile

Update golang image and pin busybox image

Update golang image and pin busybox image

---

.github/workflows/push.yml
Makefile
hack/ci/build_util.sh

Signed-off-by: danfengl <danfengl@vmware.com>

Upload image build by Make CI to gcloud

---

.github/workflows/push.yml
Makefile
hack/ci/build_util.sh

Signed-off-by: danfengl <danfengl@vmware.com>

Cherry-pick: 1.6 Upload image build by Make CI to gcloud

---

Dockerfile
hack/docker-push.sh

Use uclibc variant of busybox instead

Use uclibc variant of busybox instead

---

README.md

Update readme to clarify the content handled by object store plugin

Update readme to clarify the content handled by object store plugin

---

changelogs/CHANGELOG-1.7.0.md
changelogs/unreleased/111-yvespp
changelogs/unreleased/162-blackpiglet
changelogs/unreleased/170-blackpiglet

Add changelog for 1.7.0

---

Dockerfile
hack/cp-plugin/main.go

Use a simple program to copy the plugin binary, so that we will not depend on busybox.

Replace the cp from busybox - 1.7.x

---

.github/workflows/pr.yaml
.github/workflows/push.yml
Dockerfile
README.md

Update compatibility box and bump Golang version

Update compatibility box and bump Golang version

---

velero-plugin-for-microsoft-azure/volume_snapshotter.go

Use the subscription of VSL if provided
Fixes [#6231](https://github.com/vmware-tanzu/velero/issues/6231)

Use the subscription of VSL if provided

---

velero-plugin-for-microsoft-azure/volume_snapshotter.go

Use the subscription of VSL if provided
Fixes https://github.com/vmware-tanzu/velero/issues/6231

[cherry-pick]Use the subscription of VSL if provided

---

README.md
backupstoragelocation.md
velero-plugin-for-microsoft-azure/object_store.go
velero-plugin-for-microsoft-azure/object_store_integration_test.go

Fixes: https://github.com/vmware-tanzu/velero/issues/6163

Fix SA URI fetch and add useAAD, storageAccountUri fields

---

README.md

Json parsing errors in line 18 column 4 (char 891) and line 26 column 4 (char 1316) for create custom role block are addressed.

Fixed json parsing errors in README.md

---

README.md

Update README for supporting AAD Workload Identity

Update README for supporting AAD Workload Identity

---

.github/workflows/pr.yaml
.github/workflows/push.yml
Dockerfile
go.mod
go.sum

Align the referenced Velero version to v1.11.0.

Bump Golang version to v1.20.6

---

README.md

Update doc to fix the "DataActions"

Update doc to fix the "DataActions"

---

README.md

Update README to include the "AZURE_ENVIRONMENT" in the credential file to workaround non public cloud issue

Update README to include the "AZURE_ENVIRONMENT" in the credential file to workaround non public cloud issue

---

README.md
changelogs/CHANGELOG-1.8.0.md

Update doc and changelog for 1.8.0

Update doc and changelog for 1.8.0

---

.github/workflows/pr.yaml
.github/workflows/push.yml
Dockerfile
go.mod
go.sum

Pin version of Golang and Velero

Pin version of Golang and Velero

---

go.mod
go.sum

Bump Velero version to v1.12.0-rc.2

Bump Velero version to v1.12.0-rc.2

---

go.mod
go.sum

Pin velero version to v1.12.0

---

backupstoragelocation.md
velero-plugin-for-microsoft-azure/object_store.go
velero-plugin-for-microsoft-azure/object_store_test.go

Adjust the buffer size to avoid OOM
Fixes https://github.com/vmware-tanzu/velero/issues/6847

[cherry-pick]Adjust the buffer size to avoid OOM

---

README.md
backupstoragelocation.md

Fixes: https://github.com/vmware-tanzu/velero/issues/7168

Fix docs around storageaccounturi

---

go.mod
go.sum

Upgrade the Velero to the latest commit of main branch

Upgrade the Velero to the latest commit of main branch

---

.github/workflows/pr.yaml
.github/workflows/push.yml
Dockerfile
go.mod
go.sum

Pin the version of Golang and velero

Pin the version of Golang and velero

---

go.mod
go.sum

Bump up velero to 1.13.0-rc.2

---

go.mod
go.sum

Pin velero version as v1.13.0

---

go.mod
go.sum

Bump up Velero version

---

go.mod
go.sum

Pin Velero version to v1.13.1

---

.github/workflows/pr.yaml
.github/workflows/push.yml
Dockerfile
go.mod
go.sum

Bump the version of Golang and protobuf

Bump the version of Golang and protobuf

---

.github/workflows/pr.yaml
.github/workflows/push.yml
Dockerfile
go.mod

Bump up the version of Golang to 1.22

Bump up the version of Golang to 1.22

---

README.md
changelogs/CHANGELOG-1.10.0.md

Add changelog for v1.10.0

---

.github/workflows/pr.yaml
.github/workflows/push.yml
Dockerfile
go.mod
go.sum

Bump up the version of Golang and Velero

Bump up the version of Golang and Velero

---

go.mod
go.sum

Bump up Velero version to v1.14.0-rc.1

Bump up Velero version to v1.14.0-rc.1

---

go.mod
go.sum

Bump up the version of Velero to RC2

Bump up the version of Velero to RC2

---

go.mod
go.sum

Bump up Velero to RC3

---

go.mod
go.sum

Pin Velero to v1.14.0

---

go.mod
go.sum

Bump up Velero to 1.15.0-rc.2

---

go.mod
go.sum

Pin Velero version as v1.15.0

---

.github/workflows/push.yml

Fixes https://github.com/vmware-tanzu/velero/issues/8522

main: push.yml python3

---

go.mod
go.sum

go/x/net v0.33.0

---

.github/workflows/push.yml

Bump up the actions and fix the error pushing image to GCR
Signed-off-by: Daniel Jiang <daniel.jiang@broadcom.com>
Signed-off-by: Tiger Kaovilai <tkaovila@redhat.com>

main: Fix the issue pushing image to GCR

---

.github/workflows/pr.yaml
.github/workflows/push.yml
Dockerfile
go.mod
go.sum

Bump up versions of Golang and Velero

Bump up versions of Golang and Velero

---

go.mod
go.sum

Pin Velero version as v1.15.1

---

Dockerfile
go.mod
go.sum

Signed-off-by: Tiger Kaovilai <tkaovila@redhat.com>

CVE-2025-22868 go-mod-upgrade: golang.org/x/oauth2@v0.27.0

---

Dockerfile
README.md
changelogs/CHANGELOG-1.12.0.md
go.mod
go.sum

Also add the changelog for v1.12.0.
Modify the README.

Bump the Velero and Golang version for release-1.12.

---

go.mod
go.sum

Bump up Velero to 1.16.0-rc.2
