backupstoragelocation.md, changelogs/unreleased/00001-carlisia.md, changelogs/unreleased/30-skriss, velero-plugin-for-microsoft-azure/main.go, velero-plugin-for-microsoft-azure/object_store.go, velero-plugin-for-microsoft-azure/object_store_test.go
closes #26 
I've pushed a dev image containing this change to `steveheptio/velero-plugin-for-microsoft-azure:chunk-objects`.
=> chunk objects when uploading via PutObject

README.md, backupstoragelocation.md, velero-plugin-for-microsoft-azure/common.go, velero-plugin-for-microsoft-azure/object_store.go
=> Add support setting Storage Account Key via configuration

velero-plugin-for-microsoft-azure/object_store.go
cc @tabishis
The `storageAccountKeyEnvVar` config key was added in #32, but the validation wasn't updated to allow it as a valid key. This PR fixes that.
=> bug fix: allow storageAccountKeyEnvVar as a config key

README.md, backupstoragelocation.md, velero-plugin-for-microsoft-azure/object_store.go
After helping troubleshoot the recent thread in https://github.com/vmware-tanzu/velero/issues/2272, I made some improvements to the Azure plugin docs around how to use the storage account access key method of authentication.
=> improve docs around using static storage account keys

README.md, changelogs/unreleased/51-gitirabassi, go.mod, go.sum, velero-plugin-for-microsoft-azure/common.go, velero-plugin-for-microsoft-azure/object_store.go, velero-plugin-for-microsoft-azure/volume_snapshotter.go
updates/replaces #29 
closes #11 
closes #12
=> support aad-pod-identity auth

changelogs/unreleased/52-stephanwehr, velero-plugin-for-microsoft-azure/volume_snapshotter.go, volumesnapshotlocation.md
Closes #25 
Passed the following test cases:
Test: Omit parameter "incremental"
Result: Full snapshot taken
Test: Set parameter "incremental" to "true"
Result: Incremental snapshot taken
Test: Set parameter "incremental" to "test value"
Result: Backup fails partially, no snapshot taken, error message in log
=> add support for incremental snapshots of Azure disks

velero-plugin-for-microsoft-azure/object_store.go
When listing blobs, each page may have up to the max results (default 5000).  However: you may still get less than that amount. To get all results, azure requires us to paginate through them using NextMarker/Marker until NextMarker is unset in the response. Currently only the first page is ever considered, since this is called only once.
This fix affects the Backup Sync Controller which uses these to list the available backups and delete orphaned backups if they are not found in storage. When providing an incomplete list of results, the controller erroneously removes backup resources from the cluster when they still exist in storage.
Signed-off-by: Justen Walker <justen.walker@gmail.com>
=> fix: missing results in ListObjects/CommonPrefixes

changelogs/CHANGELOG-1.1.2.md
The PR included in the release changelog (#87) did not include a changelog
file so this has been added manually by me.
Signed-off-by: Bridget McErlean <bmcerlean@vmware.com>
=> Add changelogs for v1.1.2

README.md, changelogs/unreleased/85-justbert
I'm currently in the midst of setting up the least required permissions by the plugin to perform the necessary operations and figured it would be good to upstream the information to allow others to adhere to the principle of least access.
=> Add documentation around minimum required permissions

README.md, changelogs/unreleased/90-zubron, velero-plugin-for-microsoft-azure/common.go, velero-plugin-for-microsoft-azure/object_store.go, velero-plugin-for-microsoft-azure/volume_snapshotter.go
Add a new supported key to the config (`credentialsFile`) which allows
the path to a credentials file to be passed through to the ObjectStore
plugin. If that key is set in the config, use that file as the
credentials file to load the Azure environment variables from.
Fixes vmware-tanzu/velero#3429.
Signed-off-by: Bridget McErlean <bmcerlean@vmware.com>
=> Use credentials file passed through config

velero-plugin-for-microsoft-azure/volume_snapshotter.go, velero-plugin-for-microsoft-azure/volume_snapshotter_test.go
Current VolumeSnapshotter works with volumes allocated by the "in-tree" storage driver. Kubernetes is moving to the CSI driver for Azure and will deprecate the in-tree driver, however we may not be able to get CSI snapshots in Velero to GA before that happens. As an interim solution, we handle volumes created by the CSI driver with the existing VolumeSnapshotter.
Fixes https://github.com/vmware-tanzu/velero/issues/4109
=> Handle the volumes created by the CSI driver

go.mod, go.sum, velero-plugin-for-microsoft-azure/volume_snapshotter.go
Signed-off-by: dymurray <dymurray@redhat.com>
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3538
This PR removes dependence on `github.com/satori/uuid`
=> Updates to resolve CVE-2021-3538

.github/workflows/push.yml, Dockerfile, Makefile, hack/docker-push.sh
Ported changes from https://github.com/vmware-tanzu/velero-plugin-for-gcp/pull/78 here to improve the build process and make it consistent across plugins. Adresses https://github.com/vmware-tanzu/velero/issues/4647
A test run of the action was done here:
https://github.com/vchrisb/velero-plugin-for-microsoft-azure/actions/runs/1845613007
and the created image is available here: 
https://hub.docker.com/repository/docker/vchrisb/velero-plugin-for-microsoft-azure/tags?page=1&ordering=last_updated
=> Enhance multi arch build using buildx

.github/auto-assignees.yml, README.md, changelogs/unreleased/133-ywk253100
Refine the minimum permissions needed by Velero in README
=> Refine the minimum permissions needed by Velero in README

velero-plugin-for-microsoft-azure/object_store.go, velero-plugin-for-microsoft-azure/volume_snapshotter.go
fixes authoriser endpoints for AzureChinaCloud support (and other Azure environments)
background:
Azure REST authoriser expects environment variable `AZURE_ENVIRONMENT` but velero is using `AZURE_CLOUD_NAME`.
fixes https://github.com/vmware-tanzu/velero/issues/3440#issuecomment-1024326143
=> Fix azure environment support

Dockerfile
See discussion in: https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/135
=> use scratch as baseimage for plugin

README.md
Use the environment variable `AZURE_ROLE` defined just before when creating the custom role in README.
Signed-off-by:  Takuya Kawabuchi <tbuchi888@users.noreply.github.com>
=> Use the environment variable when creating the custom role in README

.github/workflows/pr.yaml, .github/workflows/push.yml, Dockerfile
Bump up Golang to 1.17.11 for Azure plugin 1.5
=> Bump up Golang to 1.17.11 for Azure plugin 1.5

.github/workflows/pr.yaml, .github/workflows/push.yml, Dockerfile, README.md, go.mod, velero-plugin-for-microsoft-azure/volume_snapshotter.go
1. Update the snapshotter to support VSL credential
2. Bump up golang to v1.18
3. Remove restic related
Fixes https://github.com/vmware-tanzu/velero/issues/5392 Also related to https://github.com/vmware-tanzu/velero/pull/5313 and https://github.com/vmware-tanzu/velero/issues/5274
=> Update the snapshotter to support VSL credential and bump up golang

.github/workflows/pr.yaml, .github/workflows/push.yml, Dockerfile, go.mod
Bump up golang to 1.18 to fix CVEs
=> Bump up golang to 1.18 to fix CVEs

.github/workflows/pr.yaml, .github/workflows/push.yml, Dockerfile
Pin the Golang version to v1.18.8 for v1.6.0
=> Pin the Golang version to v1.18.8 for v1.6.0

.github/workflows/pr.yaml, .github/workflows/push.yml, Dockerfile
Bump up the golang version to 1.18.10
=> Bump up the golang version to 1.18.10

README.md, backupstoragelocation.md
We introduced changes in #111 to remove the logic of listing storage account access key, the Velero Azure plugin supports auth via Azure AD directly after the changes, but that isn't enough as Restic/Kopia still doesn't support auth via Azure AD at this moment, this will cause filesystem backup failure on Azure.
So we revert the doc change in this commit and Velero still needs the permission of listing storage access key to work as expected. But as we keep the code changes, users can workaround the permission issue by refer to https://github.com/vmware-tanzu/velero/issues/5984
=> Revert the changes made to doc in #111

velero-plugin-for-microsoft-azure/object_store.go
adding environment variables in the credentials file. This can work, but the environment variables must be loaded early so that functions requiring those variables work correctly.
---
For testing this patch, I build the plugin container and deployed it to a govcloud AKS cluster. Details on why this has to be tested in govcloud in the bug report at https://github.com/vmware-tanzu/velero/issues/6196, specifically in the comment https://github.com/vmware-tanzu/velero/issues/6196#issuecomment-1523810703
=> The velero-plugin-formicrosoft-azure docs have started advising

velero-plugin-for-microsoft-azure/object_store.go
Read subscriptionID from credential if not provided in BSL
Fixes https://github.com/vmware-tanzu/velero/issues/6180
=> Read subscriptionID from credential if not provided in BSL

velero-plugin-for-microsoft-azure/object_store.go
Read subscriptionID from credential if not provided in BSL
Fixes https://github.com/vmware-tanzu/velero/issues/6180
=> [main]Read subscriptionID from credential if not provided in BSL

.github/workflows/pr.yaml, .github/workflows/push.yml, Dockerfile, Makefile, README.md
Add pushing the image to gcr.io in push action.
Bump Golang version to v1.20.
Update the compatibility box in README.md.
=> Add pushing image to gcr.io in push action.

README.md, backupstoragelocation.md, velero-plugin-for-microsoft-azure/object_store.go, velero-plugin-for-microsoft-azure/object_store_integration_test.go, velero-plugin-for-microsoft-azure/volume_snapshotter.go, volumesnapshotlocation.md
Why:
This feature pull request allows the user to define the storage endpoints and azure active directory endpoints. This is needed for azure gov / other regions where the directory and storage endpoints aren't public and do not fall under the default provided clouds. 
Additions:
- Go Int Tests to verify that the output is as expected
- Added new backupstoragelocation config values
- activeDirectoryAuthorityURI
- Added new volumesnapshotlocation config values
- activeDirectoryAuthorityURI
=> Added the capability to add custom endpoints for storage and azure active directory endpoint

backupstoragelocation.md, velero-plugin-for-microsoft-azure/object_store.go, velero-plugin-for-microsoft-azure/object_store_test.go
Adjust the buffer size to avoid OOM
Fixes https://github.com/vmware-tanzu/velero/issues/6847
=> Adjust the buffer size to avoid OOM

go.mod, go.sum, velero-plugin-for-microsoft-azure/volume_snapshotter.go
Bump version of Azure Compute SDK to support Prem SSD V2
Fixes https://github.com/vmware-tanzu/velero/issues/6650
=> Bump version of Azure Compute SDK to support Prem SSD V2

velero-plugin-for-microsoft-azure/volume_snapshotter.go
Bug fix: validate the subscription ID when initing the plugin
=> Bug fix: validate the subscription ID when initing the plugin

README.md, changelogs/CHANGELOG-1.9.0.md
Update README and changelog for 1.9.0
=> Update README and changelog for 1.9.0

README.md
Fixes: https://github.com/vmware-tanzu/velero/issues/4735
https://github.com/vmware-tanzu/velero/issues/7309
=> Add tips for incremental snapshot

go.mod, go.sum
The go-plugin libs is upgraded in Velero, this commit upgrades the Velero version to align
=> Bump up version of Velero
